# Generated by Django 5.0.3 on 2024-03-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
