# Generated by Django 5.0.3 on 2024-03-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
